Repository XRTK/WindowsMixedReality, pull requests merged in 2020-05, with the labels that each got.

#78 Added preview package capabilities
  .gitignore
  XRTK.WindowsMixedReality/Assets/XRTK.Generated.meta
  XRTK.WindowsMixedReality/Assets/XRTK.Generated/SymbolicLinkSettings.asset
  XRTK.WindowsMixedReality/Assets/XRTK.Generated/SymbolicLinkSettings.asset.meta
  XRTK.WindowsMixedReality/Assets/XRTK.Generated/WindowsMixedReality.meta
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
  XRTK.WindowsMixedReality/Packages/manifest.json
  azure-pipelines.yml
  azure_pipelines/common.yml
  azure_pipelines/stages/publish.yml
  azure_pipelines/stages/steps/build-docs.yml
  azure_pipelines/stages/steps/build-unity-player.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/steps/return-unity-license.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/steps/upm-package-info.yml
  azure_pipelines/stages/unity-build.yml
Labels: Enhancement, Ready for review

#79 updated github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request_for_information.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement, Ready for review

#80 Move platform profiles from SDK to WMR package
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityControllerDataProviderProfile.asset
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityControllerDataProviderProfile.asset.meta
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityHandControllerDataProviderProfile.asset
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityHandControllerDataProviderProfile.asset.meta
Labels: Ready for review

#81 fixed data provider serialization
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityControllerDataProviderProfile.asset
Labels: Bug

#82 Update default near clip plane for transparent display
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/CameraSystem/WindowsMixedRealityCameraProviderProfile.asset
Labels: Ready for review

#84 cleaned up wmr controller a bit
  XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/InputSystem/Controllers/WindowsMixedRealityMotionController.cs
Labels: Ready for review
